"""region→장기예보 권역 매핑 + weather_outlook 평년값/비슷구간 컬럼 (DB.md §3.12)

Revision ID: 0009
Revises: 0008
Create Date: 2026-07-25

기상청 3개월전망 RSS는 13개 권역(전국+12) 단위로만 나오는데 우리 region은 시/군 256개다.
그 매핑을 마스터 시드로 고정한다(런타임 추론 금지 — CLAUDE.md §10).

- 시/도 → 권역은 명시 대응. 시드의 '전남광주통합특별시'는 KMA의 '광주ㆍ전라남도'와 이름이
  달라 문자열 매칭이 불가능하다.
- 강원 영서/영동은 시/군 단위로 갈려 sido로 유도할 수 없어 열거한다.
- 태백시는 영서/영동 공식 분류 근거를 찾지 못해 전국 권역으로 폴백하고 is_fallback=true로
  남긴다(추측으로 지역값을 단정하지 않음 — CLAUDE.md §18-4). UI에 '권역 미특정' 병기 대상.

weather_outlook에 normal_value/similar_low/similar_high를 추가한다. RSS가 권역 평년값과
'비슷' 구간을 함께 주므로 보정 단위 δ를 상수로 추측하지 않고 데이터에서 유도할 수 있다
(DB.md §10 미결정 해소). 비슷구간은 평년값 기준 **비대칭**이라(실측 예: 평년 296.6,
구간 209.3~374.4) 단일 δ로 뭉개지 않고 양쪽 경계를 그대로 보관한다.

시드는 scripts/gen_outlook_zone_seed.py가 docs/seed/region_seed.csv에서 생성했다.
"""
from collections.abc import Sequence

from alembic import op

revision: str = "0009"
down_revision: str | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE region_outlook_zone (
            region_id   INTEGER PRIMARY KEY REFERENCES region(id),
            zone_name   VARCHAR(40) NOT NULL,
            is_fallback BOOLEAN NOT NULL DEFAULT false
        );

        ALTER TABLE weather_outlook
            ADD COLUMN normal_value NUMERIC,
            ADD COLUMN similar_low  NUMERIC,
            ADD COLUMN similar_high NUMERIC;
        """
    )
    op.execute(
        """
        INSERT INTO region_outlook_zone (region_id, zone_name, is_fallback) VALUES
    (1, '서울ㆍ인천ㆍ경기도', false),
    (2, '서울ㆍ인천ㆍ경기도', false),
    (3, '서울ㆍ인천ㆍ경기도', false),
    (4, '서울ㆍ인천ㆍ경기도', false),
    (5, '서울ㆍ인천ㆍ경기도', false),
    (6, '서울ㆍ인천ㆍ경기도', false),
    (7, '서울ㆍ인천ㆍ경기도', false),
    (8, '서울ㆍ인천ㆍ경기도', false),
    (9, '서울ㆍ인천ㆍ경기도', false),
    (10, '서울ㆍ인천ㆍ경기도', false),
    (11, '서울ㆍ인천ㆍ경기도', false),
    (12, '서울ㆍ인천ㆍ경기도', false),
    (13, '서울ㆍ인천ㆍ경기도', false),
    (14, '서울ㆍ인천ㆍ경기도', false),
    (15, '서울ㆍ인천ㆍ경기도', false),
    (16, '서울ㆍ인천ㆍ경기도', false),
    (17, '서울ㆍ인천ㆍ경기도', false),
    (18, '서울ㆍ인천ㆍ경기도', false),
    (19, '서울ㆍ인천ㆍ경기도', false),
    (20, '서울ㆍ인천ㆍ경기도', false),
    (21, '서울ㆍ인천ㆍ경기도', false),
    (22, '서울ㆍ인천ㆍ경기도', false),
    (23, '서울ㆍ인천ㆍ경기도', false),
    (24, '서울ㆍ인천ㆍ경기도', false),
    (25, '서울ㆍ인천ㆍ경기도', false),
    (26, '광주ㆍ전라남도', false),
    (27, '광주ㆍ전라남도', false),
    (28, '광주ㆍ전라남도', false),
    (29, '광주ㆍ전라남도', false),
    (30, '광주ㆍ전라남도', false),
    (31, '광주ㆍ전라남도', false),
    (32, '광주ㆍ전라남도', false),
    (33, '광주ㆍ전라남도', false),
    (34, '광주ㆍ전라남도', false),
    (35, '광주ㆍ전라남도', false),
    (36, '광주ㆍ전라남도', false),
    (37, '광주ㆍ전라남도', false),
    (38, '광주ㆍ전라남도', false),
    (39, '광주ㆍ전라남도', false),
    (40, '광주ㆍ전라남도', false),
    (41, '광주ㆍ전라남도', false),
    (42, '광주ㆍ전라남도', false),
    (43, '광주ㆍ전라남도', false),
    (44, '광주ㆍ전라남도', false),
    (45, '광주ㆍ전라남도', false),
    (46, '광주ㆍ전라남도', false),
    (47, '광주ㆍ전라남도', false),
    (48, '광주ㆍ전라남도', false),
    (49, '광주ㆍ전라남도', false),
    (50, '광주ㆍ전라남도', false),
    (51, '광주ㆍ전라남도', false),
    (52, '광주ㆍ전라남도', false),
    (53, '부산ㆍ울산ㆍ경상남도', false),
    (54, '부산ㆍ울산ㆍ경상남도', false),
    (55, '부산ㆍ울산ㆍ경상남도', false),
    (56, '부산ㆍ울산ㆍ경상남도', false),
    (57, '부산ㆍ울산ㆍ경상남도', false),
    (58, '부산ㆍ울산ㆍ경상남도', false),
    (59, '부산ㆍ울산ㆍ경상남도', false),
    (60, '부산ㆍ울산ㆍ경상남도', false),
    (61, '부산ㆍ울산ㆍ경상남도', false),
    (62, '부산ㆍ울산ㆍ경상남도', false),
    (63, '부산ㆍ울산ㆍ경상남도', false),
    (64, '부산ㆍ울산ㆍ경상남도', false),
    (65, '부산ㆍ울산ㆍ경상남도', false),
    (66, '부산ㆍ울산ㆍ경상남도', false),
    (67, '부산ㆍ울산ㆍ경상남도', false),
    (68, '부산ㆍ울산ㆍ경상남도', false),
    (69, '대구ㆍ경상북도', false),
    (70, '대구ㆍ경상북도', false),
    (71, '대구ㆍ경상북도', false),
    (72, '대구ㆍ경상북도', false),
    (73, '대구ㆍ경상북도', false),
    (74, '대구ㆍ경상북도', false),
    (75, '대구ㆍ경상북도', false),
    (76, '대구ㆍ경상북도', false),
    (77, '대구ㆍ경상북도', false),
    (78, '서울ㆍ인천ㆍ경기도', false),
    (79, '서울ㆍ인천ㆍ경기도', false),
    (80, '서울ㆍ인천ㆍ경기도', false),
    (81, '서울ㆍ인천ㆍ경기도', false),
    (82, '서울ㆍ인천ㆍ경기도', false),
    (83, '서울ㆍ인천ㆍ경기도', false),
    (84, '서울ㆍ인천ㆍ경기도', false),
    (85, '서울ㆍ인천ㆍ경기도', false),
    (86, '서울ㆍ인천ㆍ경기도', false),
    (87, '서울ㆍ인천ㆍ경기도', false),
    (88, '서울ㆍ인천ㆍ경기도', false),
    (89, '대전ㆍ세종ㆍ충청남도', false),
    (90, '대전ㆍ세종ㆍ충청남도', false),
    (91, '대전ㆍ세종ㆍ충청남도', false),
    (92, '대전ㆍ세종ㆍ충청남도', false),
    (93, '대전ㆍ세종ㆍ충청남도', false),
    (94, '부산ㆍ울산ㆍ경상남도', false),
    (95, '부산ㆍ울산ㆍ경상남도', false),
    (96, '부산ㆍ울산ㆍ경상남도', false),
    (97, '부산ㆍ울산ㆍ경상남도', false),
    (98, '부산ㆍ울산ㆍ경상남도', false),
    (99, '대전ㆍ세종ㆍ충청남도', false),
    (100, '서울ㆍ인천ㆍ경기도', false),
    (101, '서울ㆍ인천ㆍ경기도', false),
    (102, '서울ㆍ인천ㆍ경기도', false),
    (103, '서울ㆍ인천ㆍ경기도', false),
    (104, '서울ㆍ인천ㆍ경기도', false),
    (105, '서울ㆍ인천ㆍ경기도', false),
    (106, '서울ㆍ인천ㆍ경기도', false),
    (107, '서울ㆍ인천ㆍ경기도', false),
    (108, '서울ㆍ인천ㆍ경기도', false),
    (109, '서울ㆍ인천ㆍ경기도', false),
    (110, '서울ㆍ인천ㆍ경기도', false),
    (111, '서울ㆍ인천ㆍ경기도', false),
    (112, '서울ㆍ인천ㆍ경기도', false),
    (113, '서울ㆍ인천ㆍ경기도', false),
    (114, '서울ㆍ인천ㆍ경기도', false),
    (115, '서울ㆍ인천ㆍ경기도', false),
    (116, '서울ㆍ인천ㆍ경기도', false),
    (117, '서울ㆍ인천ㆍ경기도', false),
    (118, '서울ㆍ인천ㆍ경기도', false),
    (119, '서울ㆍ인천ㆍ경기도', false),
    (120, '서울ㆍ인천ㆍ경기도', false),
    (121, '서울ㆍ인천ㆍ경기도', false),
    (122, '서울ㆍ인천ㆍ경기도', false),
    (123, '서울ㆍ인천ㆍ경기도', false),
    (124, '서울ㆍ인천ㆍ경기도', false),
    (125, '서울ㆍ인천ㆍ경기도', false),
    (126, '서울ㆍ인천ㆍ경기도', false),
    (127, '서울ㆍ인천ㆍ경기도', false),
    (128, '서울ㆍ인천ㆍ경기도', false),
    (129, '서울ㆍ인천ㆍ경기도', false),
    (130, '서울ㆍ인천ㆍ경기도', false),
    (131, '서울ㆍ인천ㆍ경기도', false),
    (132, '서울ㆍ인천ㆍ경기도', false),
    (133, '서울ㆍ인천ㆍ경기도', false),
    (134, '서울ㆍ인천ㆍ경기도', false),
    (135, '서울ㆍ인천ㆍ경기도', false),
    (136, '서울ㆍ인천ㆍ경기도', false),
    (137, '서울ㆍ인천ㆍ경기도', false),
    (138, '서울ㆍ인천ㆍ경기도', false),
    (139, '서울ㆍ인천ㆍ경기도', false),
    (140, '서울ㆍ인천ㆍ경기도', false),
    (141, '서울ㆍ인천ㆍ경기도', false),
    (142, '서울ㆍ인천ㆍ경기도', false),
    (143, '서울ㆍ인천ㆍ경기도', false),
    (144, '서울ㆍ인천ㆍ경기도', false),
    (145, '서울ㆍ인천ㆍ경기도', false),
    (146, '서울ㆍ인천ㆍ경기도', false),
    (147, '충청북도', false),
    (148, '충청북도', false),
    (149, '충청북도', false),
    (150, '충청북도', false),
    (151, '충청북도', false),
    (152, '충청북도', false),
    (153, '충청북도', false),
    (154, '충청북도', false),
    (155, '충청북도', false),
    (156, '충청북도', false),
    (157, '충청북도', false),
    (158, '충청북도', false),
    (159, '충청북도', false),
    (160, '충청북도', false),
    (161, '대전ㆍ세종ㆍ충청남도', false),
    (162, '대전ㆍ세종ㆍ충청남도', false),
    (163, '대전ㆍ세종ㆍ충청남도', false),
    (164, '대전ㆍ세종ㆍ충청남도', false),
    (165, '대전ㆍ세종ㆍ충청남도', false),
    (166, '대전ㆍ세종ㆍ충청남도', false),
    (167, '대전ㆍ세종ㆍ충청남도', false),
    (168, '대전ㆍ세종ㆍ충청남도', false),
    (169, '대전ㆍ세종ㆍ충청남도', false),
    (170, '대전ㆍ세종ㆍ충청남도', false),
    (171, '대전ㆍ세종ㆍ충청남도', false),
    (172, '대전ㆍ세종ㆍ충청남도', false),
    (173, '대전ㆍ세종ㆍ충청남도', false),
    (174, '대전ㆍ세종ㆍ충청남도', false),
    (175, '대전ㆍ세종ㆍ충청남도', false),
    (176, '대전ㆍ세종ㆍ충청남도', false),
    (177, '대구ㆍ경상북도', false),
    (178, '대구ㆍ경상북도', false),
    (179, '대구ㆍ경상북도', false),
    (180, '대구ㆍ경상북도', false),
    (181, '대구ㆍ경상북도', false),
    (182, '대구ㆍ경상북도', false),
    (183, '대구ㆍ경상북도', false),
    (184, '대구ㆍ경상북도', false),
    (185, '대구ㆍ경상북도', false),
    (186, '대구ㆍ경상북도', false),
    (187, '대구ㆍ경상북도', false),
    (188, '대구ㆍ경상북도', false),
    (189, '대구ㆍ경상북도', false),
    (190, '대구ㆍ경상북도', false),
    (191, '대구ㆍ경상북도', false),
    (192, '대구ㆍ경상북도', false),
    (193, '대구ㆍ경상북도', false),
    (194, '대구ㆍ경상북도', false),
    (195, '대구ㆍ경상북도', false),
    (196, '대구ㆍ경상북도', false),
    (197, '대구ㆍ경상북도', false),
    (198, '대구ㆍ경상북도', false),
    (199, '대구ㆍ경상북도', false),
    (200, '부산ㆍ울산ㆍ경상남도', false),
    (201, '부산ㆍ울산ㆍ경상남도', false),
    (202, '부산ㆍ울산ㆍ경상남도', false),
    (203, '부산ㆍ울산ㆍ경상남도', false),
    (204, '부산ㆍ울산ㆍ경상남도', false),
    (205, '부산ㆍ울산ㆍ경상남도', false),
    (206, '부산ㆍ울산ㆍ경상남도', false),
    (207, '부산ㆍ울산ㆍ경상남도', false),
    (208, '부산ㆍ울산ㆍ경상남도', false),
    (209, '부산ㆍ울산ㆍ경상남도', false),
    (210, '부산ㆍ울산ㆍ경상남도', false),
    (211, '부산ㆍ울산ㆍ경상남도', false),
    (212, '부산ㆍ울산ㆍ경상남도', false),
    (213, '부산ㆍ울산ㆍ경상남도', false),
    (214, '부산ㆍ울산ㆍ경상남도', false),
    (215, '부산ㆍ울산ㆍ경상남도', false),
    (216, '부산ㆍ울산ㆍ경상남도', false),
    (217, '부산ㆍ울산ㆍ경상남도', false),
    (218, '부산ㆍ울산ㆍ경상남도', false),
    (219, '부산ㆍ울산ㆍ경상남도', false),
    (220, '부산ㆍ울산ㆍ경상남도', false),
    (221, '부산ㆍ울산ㆍ경상남도', false),
    (222, '제주도', false),
    (223, '제주도', false),
    (224, '강원도 영서', false),
    (225, '강원도 영서', false),
    (226, '강원도 영동', false),
    (227, '강원도 영동', false),
    (228, '전국(제주도,북한제외)', true),
    (229, '강원도 영동', false),
    (230, '강원도 영동', false),
    (231, '강원도 영서', false),
    (232, '강원도 영서', false),
    (233, '강원도 영서', false),
    (234, '강원도 영서', false),
    (235, '강원도 영서', false),
    (236, '강원도 영서', false),
    (237, '강원도 영서', false),
    (238, '강원도 영서', false),
    (239, '강원도 영서', false),
    (240, '강원도 영동', false),
    (241, '강원도 영동', false),
    (242, '전북자치도', false),
    (243, '전북자치도', false),
    (244, '전북자치도', false),
    (245, '전북자치도', false),
    (246, '전북자치도', false),
    (247, '전북자치도', false),
    (248, '전북자치도', false),
    (249, '전북자치도', false),
    (250, '전북자치도', false),
    (251, '전북자치도', false),
    (252, '전북자치도', false),
    (253, '전북자치도', false),
    (254, '전북자치도', false),
    (255, '전북자치도', false),
    (256, '전북자치도', false)
        ON CONFLICT (region_id) DO UPDATE
            SET zone_name = EXCLUDED.zone_name, is_fallback = EXCLUDED.is_fallback;
        """
    )


def downgrade() -> None:
    op.execute(
        """
        DROP TABLE IF EXISTS region_outlook_zone;

        ALTER TABLE weather_outlook
            DROP COLUMN IF EXISTS normal_value,
            DROP COLUMN IF EXISTS similar_low,
            DROP COLUMN IF EXISTS similar_high;
        """
    )
